[common info]
url = https://adnabu-store-assignment1.myshopify.com/password
PW = AdNabuQA
productName = The Videographer Snowboard
url_shop = adnabu-store-assignment1.myshopify.com

[locators]
# Landing Page
passwordTextBox_ID = password
submitPasswordButton_XPATH = //button[text()='Enter']
# Search Logic
clickSearchIcon_CSS = .modal__toggle-open.icon.icon-search
inputSearchBox_XPATH = (//input[@id='Search-In-Modal'])[1]
# Dynamic Item Locator
TheCompleteSnowboard_XPATH = //p[normalize-space()='{0}']
addToCartButton_XPATH = (//button[@id='ProductSubmitButton-template--19850788667482__main'])[1]
checkout_XPATH = (//button[normalize-space()='Check out'])[1]
payNowButton_XPATH = (//button[@id='checkout-pay-button'])[1]
